export const translatedFormPaths = [
  "/hr/car-rental",
  "/hr/leave",
  "/hr/ppe-request",
  "/finance/receipt-upload",
  "/finance/claim",
  "/it/cctv-access-request",
  "/it/help-desk",
  "/it/request-admin",
  "/it/request-application",
] as const;

export const supportsFormTranslation = (pathname: string) =>
  translatedFormPaths.some(path => pathname === path);

export const msFormUi: Record<string, string> = {
  "Back to HR Forms": "Kembali ke Borang HR",
  "Back to Finance Forms": "Kembali ke Borang Kewangan",
  "Back to IT Forms": "Kembali ke Borang IT",
  "Company Car Request": "Permohonan Kereta Syarikat",
  "Gate Pass": "Pas Keluar",
  "Petty Cash Claim": "Tuntutan Wang Runcit",
  "Upload Petty Cash Receipt": "Muat Naik Resit Wang Runcit",
  "CCTV Access Request": "Permohonan Akses CCTV",
  "IT Help Desk Ticket": "Tiket Meja Bantuan IT",
  "IT Request Form (Application)": "Borang Permohonan IT (Aplikasi)",
  "Employee Details": "Butiran Pekerja",
  "Employee Details / Butiran Pekerja": "Butiran Pekerja",
  "Request Details": "Butiran Permohonan",
  "Booking Details": "Butiran Tempahan",
  "Journey Details": "Butiran Perjalanan",
  "Passenger Details": "Butiran Penumpang",
  "Approval Routing": "Laluan Kelulusan",
  "Approvals": "Kelulusan",
  "Approval": "Kelulusan",
  "Requisition": "Permohonan",
  "Type of Request": "Jenis Permohonan",
  "Camera and Incident Details": "Butiran Kamera dan Kejadian",
  "Purpose of Access": "Tujuan Akses",
  "Confidentiality Declaration": "Akuan Kerahsiaan",
  "Ticket Classification": "Klasifikasi Tiket",
  "Submission Reference Number": "Nombor Rujukan Penyerahan",
  "Receipt / Invoice File(s)": "Fail Resit / Invois",
  "Name / Nama": "Nama",
  "Position / Jawatan": "Jawatan",
  "Staff ID / No. Pekerja": "No. Pekerja",
  "Department / Jabatan": "Jabatan",
  "Department Code / Kod Jabatan": "Kod Jabatan",
  "Date / Tarikh": "Tarikh",
  "Category / Kategori": "Kategori",
  "Remarks / Ulasan": "Ulasan",
  "Location / Tempat": "Tempat",
  "Purpose / Tujuan": "Tujuan",
  "Journey Type / Jenis Perjalanan": "Jenis Perjalanan",
  "From Date & Time / Dari Tarikh & Masa": "Dari Tarikh & Masa",
  "To Date & Time / Kepada Tarikh & Masa": "Hingga Tarikh & Masa",
  "Purpose of Journey / Tujuan perjalanan": "Tujuan Perjalanan",
  "Destination / Destinasi": "Destinasi",
  "Head of Section / Ketua Bahagian": "Ketua Seksyen",
  "Head of Department / Ketua Jabatan": "Ketua Jabatan",
  "Head of Section": "Ketua Seksyen",
  "Head of Department": "Ketua Jabatan",
  "Head of Purchasing": "Ketua Pembelian",
  "Head of Finance": "Ketua Kewangan",
  "Manco Members": "Ahli Manco",
  "Time Out / Masa Keluar": "Masa Keluar",
  "Time In / Masa Masuk": "Masa Masuk",
  "Upload Driving Licence": "Muat Naik Lesen Memandu",
  "Upload Invoice / Receipt": "Muat Naik Invois / Resit",
  "Size / Option": "Saiz / Pilihan",
  "Quantity": "Kuantiti",
  "Camera Location": "Lokasi Kamera",
  "Incident Date and Time": "Tarikh dan Masa Kejadian",
  "From Date & Time": "Dari Tarikh & Masa",
  "To Date & Time": "Hingga Tarikh & Masa",
  "Other Purpose": "Tujuan Lain",
  "Select all IT facilities required.": "Pilih semua kemudahan IT yang diperlukan.",
  "Select Department Code": "Pilih Kod Jabatan",
  "Choose Head of Section": "Pilih Ketua Seksyen",
  "Choose Head of Department": "Pilih Ketua Jabatan",
  "Choose Head of Purchasing": "Pilih Ketua Pembelian",
  "Choose Head of Finance": "Pilih Ketua Kewangan",
  "Choose Manco Member": "Pilih Ahli Manco",
  "Loading users...": "Memuatkan pengguna...",
  "Select the purpose of access": "Pilih tujuan akses",
  "Select superior email": "Pilih e-mel pegawai atasan",
  "Select urgency": "Pilih tahap keutamaan",
  "Select report option": "Pilih pilihan laporan",
  "Select type of issue or request": "Pilih jenis masalah atau permohonan",
  "Select at least one type of request.": "Pilih sekurang-kurangnya satu jenis permohonan.",
  "Laptop / Desktop": "Komputer Riba / Desktop",
  "Email": "E-mel",
  "Internet Access": "Akses Internet",
  "Printer": "Pencetak",
  "Personal Matter": "Urusan Peribadi",
  "Company Business": "Urusan Syarikat",
  "Other": "Lain-lain",
  "Others": "Lain-lain",
  "Cancel": "Batal",
  "Remove": "Buang",
  "Choose": "Pilih",
  "Size": "Saiz",
  "Submit Request": "Hantar Permohonan",
  "Submit Gate Pass": "Hantar Pas Keluar",
  "Submit Record": "Hantar Rekod",
  "Submit Receipt": "Hantar Resit",
  "Submit Ticket": "Hantar Tiket",
  "Submit": "Hantar",
  "Update Claim": "Kemas Kini Tuntutan",
  "Submitting...": "Sedang dihantar...",
  "Updating...": "Sedang dikemas kini...",
  "Uploading...": "Sedang dimuat naik...",
  "State the reason for your request...": "Nyatakan sebab permohonan anda...",
  "Enter name": "Masukkan nama",
  "Write the details": "Tulis butiran",
  "Enter No.": "Masukkan No.",
  "Enter the purpose of access": "Masukkan tujuan akses",
  "Describe the issue, troubleshooting details, or request...": "Terangkan masalah, langkah penyelesaian, atau permohonan...",
  "Please enter remarks if any / Sila masukkan ulasan jika ada...": "Sila masukkan ulasan jika ada...",
  "Search all access rights...": "Cari semua hak akses...",
  "Show selected only": "Tunjukkan yang dipilih sahaja",
  "No matching access rights.": "Tiada hak akses yang sepadan.",
};
